import { BlogPost } from '@/types';

// Helper function to convert content array to HTML string
const contentToHTML = (contentArray: any[]): string => {
  return contentArray.map(item => {
    if (item.type === 'heading') {
      return `<h2 class="${item.className || ''}">${item.text}</h2>`;
    } else if (item.type === 'paragraph') {
      return `<p>${item.text}</p>`;
    }
    return '';
  }).join('\n');
};

const whitelabelPPCContent = [
  { type: 'paragraph', text: "In today's rapidly evolving digital-marketing landscape, agencies are also constantly looking for ways to optimize the results of their marketing campaigns, increase their ROI and expand the services they can offer online-marketing capabilities, without overloading their in-house marketer teams." },
  { type: 'paragraph', text: "White-label PPC (Pay-Per-Click) stands out as a strategic solution, enabling agencies to provide high performance PPC campaigns, conversion rate optimization and search engine marketing under their own brand - while expert partners run the work behind-the-scenes." },
  { type: 'heading', text: 'What are White Label PPC Services?', className: 'mt-4 mb-3' },
  { type: 'paragraph', text: "White-label PPC services allow digital marketing and branding agencies to provide expert PPC management such as AdWords, paid search and display network under their own marketing platform branding. Instead of hiring new talents or investing in hours of PPC training, agencies work with specialized departments who deal with everything from landing pages and ad copy to keyword planner and bid management. This efficient model provides you with access to top-notch campaign optimization, conversion tracking and analytics top-notch, all customized to keep you with consistent agency identity." },
  { type: 'heading', text: 'Why White-Label PPC is a Must for Agencies?', className: 'mt-4 mb-3' },
  { type: 'paragraph', text: "Digital agencies are faced with the challenge of balancing client growth, ad group performance, and resource allocation." },
  { type: 'paragraph', text: "<strong>White-label PPC provides:</strong>" },
  { type: 'paragraph', text: "<strong>Scalability:</strong> Onboard more B2B and ecommerce clients, provide more marketing solutions, manage more AdWords campaigns/funnel strategies without having to increase your internal team." },
  { type: 'paragraph', text: "<strong>Expertise:</strong> Engage with content-marketing, messaging and PPC professionals who are well-versed in Google Ads, funnel strategies, and search engine optimization (SEO)." },
  { type: 'paragraph', text: "<strong>Time Efficiency:</strong> Free internal resources from ongoing campaigns, click-through, and optimization to focus on CRM, marketing strategy, client development and getting new business." },
  { type: 'paragraph', text: "<strong>Consistent Branding:</strong> Present branded dashboards, advertising campaigns, and marketing plans that reinforce the image of your agency with each client interaction." },
  { type: 'heading', text: 'Benefits Provided to Your Customers:', className: 'mt-4 mb-3' },
  { type: 'paragraph', text: "Increased ROI and conversion - Smarter targeting, segmentation and negative keywords." },
  { type: 'paragraph', text: "Advanced engine optimization, keyword research, and demographic targeting of audience for better ad copy performance." },
  { type: 'paragraph', text: "Trend and data analytics-based responsive campaign management and bid adjustments." },
  { type: 'paragraph', text: "Constant, transparent reporting and attribution, in line with the expectations of an \"in-house\" PPC team" },
  { type: 'heading', text: 'Selecting the Best White-Label PPC Partner', className: 'mt-4 mb-3' },
  { type: 'paragraph', text: "Choosing a partner is very important. Look for:" },
  { type: 'paragraph', text: "Proven track record on marketing campaigns, paid search and AdWords account management." },
  { type: 'paragraph', text: "Open, effective communication and subscriber service with effective feedback loops." },
  { type: 'paragraph', text: "Customisable solutions for unique marketing strategies, B2b marketing needs and different conversion goals." },
  { type: 'paragraph', text: "Superior tools for online presence, campaign segmentation, digital marketing services." },
  { type: 'heading', text: 'Conclusion:', className: 'mt-4 mb-3' },
  { type: 'paragraph', text: "White-label PPC is a strategic growth driver and cost-effective service for today's digital marketing agencies. It allows for scalability, quality assurance and seamless client experiences – from inbound marketing to remarketing, ad copywriting to campaign optimization, marketing analytics to influencer marketing." },
  { type: 'paragraph', text: "As an established leader in the digital space, agencies can concentrate on more creative strategies, branding and relationship building - resulting in profitable outcomes, improved marketing campaigns, and steady business growth in a competitive environment." },
  { type: 'paragraph', text: "Unlock the full potential of your agency with white label PPC, using the latest in marketing automation, data-driven attribution and ROI-driven strategies to win new customers and grow your marketing agency's reputation as a leader in the digital marketing world." },
];

export const BLOG_POSTS: BlogPost[] = [
  {
    id: '1',
    title: 'White-Label PPC: Promoting Agencies to Be Smarter in Digital Marketing',
    slug: 'white-label-ppc-digital-marketing',
    image: '/images/ppc.webp',
    category: 'Digital Marketing',
    excerpt: 'Discover how white-label PPC services enable agencies to provide high-performance campaigns, optimize ROI, and expand their digital marketing capabilities without overloading in-house teams.',
    content: contentToHTML(whitelabelPPCContent),
    author: 'Geekonomy Team',
    date: '2025-03-20',
    tags: ['Digital Marketing', 'PPC', 'White-Label', 'Agency Growth'],
  },
  {
    id: '2',
    title: 'The Future of E-Commerce: Geekonomy\'s Strategies for Online Success',
    slug: 'ecommerce-trends-shaping-2025',
    image: '/images/E_Commerce.webp',
    category: 'E-Commerce',
    excerpt: 'Explore the latest e-commerce trends and strategies that will shape online business success in 2025 and beyond.',
    content: '<p>Coming soon...</p>',
    author: 'Geekonomy Team',
    date: '2025-03-18',
    tags: ['E-Commerce', 'Online Business', 'Digital Strategy'],
  },
  {
    id: '3',
    title: 'How Geekonomy Designs Stunning Logos that Stand Out in the Market',
    slug: 'stunning-logos-design-guide',
    image: '/images/Stunning_Logos.webp',
    category: 'Branding',
    excerpt: 'Learn the principles and processes behind creating memorable logos that make brands stand out in crowded markets.',
    content: '<p>Coming soon...</p>',
    author: 'Geekonomy Team',
    date: '2025-03-15',
    tags: ['Branding', 'Logo Design', 'Visual Identity'],
  },
  {
    id: '4',
    title: 'The Power of Brand Storytelling',
    slug: 'the-power-of-brand-storytelling',
    image: '/images/Brand_Storytelling.webp',
    category: 'Branding',
    excerpt: 'Discover how compelling brand narratives create emotional connections and help brands connect meaningfully with their customers.',
    content: '<p>Coming soon...</p>',
    author: 'Geekonomy Team',
    date: '2025-03-12',
    tags: ['Branding', 'Storytelling', 'Marketing'],
  },
  {
    id: '5',
    title: 'Content Marketing in 2025: Creating Engaging Content',
    slug: 'content-marketing-2025',
    image: '/images/Content_Marketing.webp',
    category: 'Digital Marketing',
    excerpt: 'Master the art of creating engaging content that resonates with your audience and drives meaningful results.',
    content: '<p>Coming soon...</p>',
    author: 'Geekonomy Team',
    date: '2025-03-10',
    tags: ['Content Marketing', 'Digital Marketing', 'Strategy'],
  },
  {
    id: '6',
    title: 'Digital Marketing Strategies: Maximizing ROI',
    slug: 'digital-marketing-strategies-that-convert',
    image: '/images/Digital_Advertising_Strategies.webp',
    category: 'Digital Marketing',
    excerpt: 'Learn proven digital marketing strategies that maximize ROI and drive sustainable business growth.',
    content: '<p>Coming soon...</p>',
    author: 'Geekonomy Team',
    date: '2025-03-08',
    tags: ['Digital Marketing', 'ROI', 'Strategy'],
  },
  {
    id: '7',
    title: 'UX Design Trends for 2025: Creating User-Centric Experiences',
    slug: 'ux-design-principles-higher-conversions',
    image: '/images/UX_Design.webp',
    category: 'UX Design',
    excerpt: 'Stay ahead with the latest UX design trends and principles for creating exceptional user experiences.',
    content: '<p>Coming soon...</p>',
    author: 'Geekonomy Team',
    date: '2025-03-05',
    tags: ['UX Design', 'User Experience', 'Design Trends'],
  },
  {
    id: '8',
    title: 'Social Media Marketing: Building Engagement and Community',
    slug: 'customer-retention-building-loyalty',
    image: '/images/Social_Media_Marketing.webp',
    category: 'Digital Marketing',
    excerpt: 'Discover effective social media strategies for building engaged communities and fostering brand loyalty.',
    content: '<p>Coming soon...</p>',
    author: 'Geekonomy Team',
    date: '2025-03-02',
    tags: ['Social Media', 'Marketing', 'Community'],
  },
  {
    id: '9',
    title: 'The Role of AI in Marketing: Leveraging Technology for Success',
    slug: 'future-of-ai-in-business',
    image: '/images/AI_Marketing.webp',
    category: 'AI & Technology',
    excerpt: 'Explore how artificial intelligence is transforming marketing and enabling data-driven business decisions.',
    content: '<p>Coming soon...</p>',
    author: 'Geekonomy Team',
    date: '2025-02-28',
    tags: ['AI', 'Marketing', 'Technology'],
  },
  {
    id: '10',
    title: 'Why Responsive Web Design is Essential: Mobile Optimizations',
    slug: 'mobile-first-development-2025',
    image: '/images/Responsive_Web_Design.webp',
    category: 'Web Development',
    excerpt: 'Learn why responsive web design is critical for success in today\'s mobile-first digital landscape.',
    content: '<p>Coming soon...</p>',
    author: 'Geekonomy Team',
    date: '2025-02-25',
    tags: ['Web Development', 'Responsive Design', 'Mobile'],
  },
  {
    id: '11',
    title: 'The Importance of SEO: Data Analytics and Insights',
    slug: 'data-analytics-turning-information-into-insights',
    image: '/images/Importance_of_SEO.webp',
    category: 'Data Analytics',
    excerpt: 'Understand how SEO and data analytics work together to drive organic traffic and business growth.',
    content: '<p>Coming soon...</p>',
    author: 'Geekonomy Team',
    date: '2025-02-20',
    tags: ['SEO', 'Data Analytics', 'Digital Marketing'],
  },
];

export const BLOG_CATEGORIES = [
  'All',
  'Branding',
  'AI & Technology',
  'Cloud Computing',
  'Mobile Development',
  'Digital Marketing',
  'Customer Success',
  'UX Design',
  'E-Commerce',
  'Data Analytics',
  'Cybersecurity',
  'Web Development',
];
